#
# TABLE STRUCTURE FOR: Course
#

DROP TABLE IF EXISTS `Course`;

CREATE TABLE `Course` (
  `course_id` int(11) NOT NULL AUTO_INCREMENT,
  `type` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `address` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `scheduled` datetime NOT NULL,
  `price` decimal(5,2) NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `instructor` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `capacity` int(11) NOT NULL,
  `citation_type_id` int(11) DEFAULT NULL,
  `school_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`course_id`),
  KEY `citation_type_id` (`citation_type_id`),
  KEY `school_id` (`school_id`),
  CONSTRAINT `Course_ibfk_1` FOREIGN KEY (`citation_type_id`) REFERENCES `Citation_Type` (`citation_type_id`),
  CONSTRAINT `Course_ibfk_2` FOREIGN KEY (`school_id`) REFERENCES `School` (`school_id`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (1, 'purdy', '6416 Labadie Skyway\nEast Bobbieshire, ME 07675-2563', 'laboriosam', '1970-04-24 21:16:49', '1.30', 'Maxime porro distinctio quasi quod deserunt quos. Consectetur aperiam et minus praesentium. Doloribus perferendis mollitia ut numquam doloribus quis ullam.', 'Aliquid reiciendis ut repellendus sapiente amet est.', 'Erin Carroll', 0, 1, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (2, 'rowehaag', '5688 Anissa Hills\nJewellport, VA 81402-9558', 'est', '2002-12-11 17:03:00', '999.99', 'Itaque deserunt ullam aut voluptatum ducimus repellat odit. Autem adipisci omnis illo. Neque cupiditate optio omnis omnis odit delectus in.', 'Quae est quia consequatur nostrum id.', 'Mr. Nikko Cremin', 0, 7, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (3, 'hellerkoepp', '6329 Funk Rest\nQuigleyshire, MO 43700-4639', 'eos', '1996-09-02 22:15:36', '0.00', 'Quis animi quia nihil tenetur assumenda quia. Voluptas aut facilis dolores maiores ut perspiciatis quod nisi. Aut sunt repudiandae omnis eos error.', 'Et temporibus dolorem dolor et rerum ab.', 'Roberto Prohaska', 0, 4, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (4, 'metz', '8456 Monte Meadow\nZiemannville, NC 14221', 'enim', '1988-01-06 12:51:38', '999.99', 'Enim dignissimos neque voluptatem consequatur est. Consectetur quis sit velit eos odit ipsum hic modi. Sunt et quasi sapiente ipsam.', 'Ullam qui nobis cupiditate quo officia.', 'Joanny Littel', 0, 8, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (5, 'hilllspencer', '59123 Eichmann Field\nMohamedhaven, SD 70022-9227', 'accusamus', '1984-04-16 15:32:20', '51.26', 'Tempore et corrupti ut laboriosam reiciendis et. Qui ullam rerum optio magni porro ducimus illo. Adipisci necessitatibus eum molestias recusandae deserunt nihil qui.', 'Sunt quam porro enim numquam.', 'Chris Botsford', 0, 7, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (6, 'leschkessler', '278 Kris Village\nNew Joanyside, MA 04210-8710', 'ratione', '1981-05-10 03:25:53', '999.99', 'Facilis ut omnis dolores nisi. Et cupiditate repudiandae nesciunt facere sit quia. Velit nam optio necessitatibus est eum.', 'Est excepturi optio quam consequuntur eaque consequatur.', 'Estefania Botsford', 0, 9, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (7, 'beier', '03245 Matilde Gardens Apt. 391\nRowefort, KY 17240', 'enim', '2009-09-21 07:31:32', '999.99', 'Quo distinctio ipsum eum iure maxime possimus reiciendis. Non delectus velit quo voluptatibus explicabo in. Velit et veniam deserunt voluptas iusto nemo quasi. Ipsa eum veniam facilis enim dolores quis qui est.', 'Quisquam id delectus ipsum iusto.', 'Dominic Hermann', 0, 1, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (8, 'kshlerinlueilwitz', '35354 Lacy Divide\nStoltenbergburgh, MT 97578-6945', 'quasi', '1998-08-20 07:35:28', '999.99', 'Autem delectus consectetur dicta aspernatur. Vero eveniet non ut unde quasi perferendis. Aliquid qui eius distinctio nisi.', 'Aliquid soluta nam error architecto aut voluptatem quam.', 'Princess Denesik', 0, 2, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (9, 'daugherty', '07347 Grady Key Suite 469\nNorth Keeley, AR 15975', 'enim', '2004-12-24 05:17:04', '999.99', 'Incidunt eum autem omnis nemo. Dicta culpa officiis quia et et cupiditate cum dignissimos. Eos atque delectus sunt consequatur reiciendis quo in suscipit. Cum cupiditate necessitatibus autem porro alias aspernatur sed. Expedita quia quod voluptates sapiente et.', 'Dolor ut explicabo in atque rerum quidem laudantium.', 'Linda Littel', 0, 7, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (10, 'brakus', '499 Nikolaus Coves Apt. 986\nCarmeloport, CT 49370', 'vero', '1972-08-05 15:51:51', '999.99', 'Est reiciendis ea dolore et exercitationem qui. Rerum suscipit asperiores sit ut. Dolorem consequatur ullam maxime consequatur commodi porro. Voluptate et voluptatem a ut animi.', 'Vero et cum rerum odio officia quas quis.', 'Mr. Raheem Ondricka', 0, 10, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (11, 'batz', '759 Marcel Mall Suite 637\nVeumland, LA 86961-8645', 'omnis', '1987-06-12 16:57:11', '756.00', 'Aut numquam ut ipsum et. Aut minus similique inventore id pariatur hic veritatis voluptatum. Enim molestiae rerum pariatur consectetur.', 'Corporis perferendis iste unde.', 'Lenna Cormier PhD', 0, 9, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (12, 'auer', '24320 Koss Lodge Apt. 628\nSouth Lorenzo, HI 07545-6339', 'magni', '1987-05-07 02:17:34', '999.99', 'Est omnis minima magni reprehenderit ullam doloremque. Iste delectus voluptates veniam eaque voluptas molestiae ut. Facere accusamus quidem rerum et quam. Repudiandae ex tenetur ut qui ut.', 'Ut ea fugiat omnis eos nemo eum.', 'Lennie Huels', 0, 6, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (13, 'rowelubowitz', '023 Tromp Fords\nNew Lennieland, SC 08957-7532', 'facere', '1981-05-10 13:03:59', '999.99', 'Dolorem optio eligendi modi quia excepturi dolor sed. Quia doloribus est velit aut mollitia. Necessitatibus veritatis consequuntur provident neque ratione reiciendis.', 'Et et voluptatem earum sit rem magnam.', 'Prof. Angelita Nikolaus', 0, 1, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (14, 'nitzschenicolas', '846 Maggio Skyway Suite 546\nMorrisshire, NV 68147', 'eligendi', '1987-08-02 07:20:34', '999.99', 'Qui ea vel ratione aut sunt. Et ut ea aperiam molestias voluptate. Aut modi eum eos ad. Veniam commodi modi mollitia velit aut labore alias.', 'Vel aut rerum non.', 'Stefan Witting', 0, 7, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (15, 'westlind', '72015 Windler Neck\nNorth Anahi, IN 50238', 'veritatis', '1995-10-27 04:08:23', '339.28', 'Voluptas officiis enim explicabo architecto. Reprehenderit quod perferendis velit non repellat a qui praesentium. Est reiciendis officia aut nisi. Rerum aspernatur fuga voluptate harum libero necessitatibus.', 'Odio voluptate impedit rem sequi dolorem.', 'Viola Johnston', 0, 7, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (16, 'lockmannikolaus', '208 Adelia Station Apt. 059\nWest Josie, SD 58173', 'laudantium', '1999-06-02 21:21:01', '1.84', 'Quisquam et nihil ut iure. Ut dignissimos velit rem aperiam. Est nihil aut odit rem. Dignissimos optio libero dolorum ut maxime voluptatibus officia qui.', 'Sed nihil voluptas voluptatem saepe sed laboriosam.', 'Charley Kshlerin III', 0, 4, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (17, 'rempel', '652 Denesik Court\nNew Piper, FL 15311', 'exercitationem', '2005-07-27 17:05:18', '9.94', 'Molestias harum similique sit. Ratione aut aut voluptatem magni ipsum maiores sed quam. Itaque sapiente similique sapiente sequi nesciunt enim eaque facere. Et quae quia est est tenetur asperiores.', 'Rerum saepe et voluptas ut quidem dolore praesentium consequatur.', 'Dr. Sid Schinner I', 0, 10, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (18, 'bogisichblock', '51583 Camilla Common Apt. 973\nLake Toneyville, ND 07654-7833', 'minima', '2020-07-14 14:49:54', '2.97', 'Vel aut voluptas aspernatur fugiat ut architecto labore dolores. Voluptas vero facilis sit quae. Illo ducimus temporibus cum.', 'Vitae architecto officia quam quasi maxime doloribus.', 'Mr. Neil Shields', 0, 10, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (19, 'legros', '1505 Monserrate Land\nStokesberg, IL 45944', 'molestias', '2005-01-23 03:47:54', '999.99', 'Similique aspernatur dignissimos quia culpa. Blanditiis quisquam et dolorum ipsam quos sequi. Deleniti debitis laborum est qui qui.', 'Fugiat sequi tenetur tempora nobis at autem.', 'Davin Bosco', 0, 6, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (20, 'collier', '1952 Bettye Village\nHilmaside, UT 12684-0173', 'nostrum', '1991-02-27 08:14:21', '999.99', 'Adipisci vel facere est delectus. Nesciunt qui possimus id id dicta aliquid. Quidem distinctio distinctio odio consequatur tempora.', 'Qui aut consequuntur blanditiis blanditiis.', 'Emilia Champlin', 0, 10, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (21, 'ullrich', '199 Lelah Route\nEast Efrenmouth, GA 83529', 'tempora', '1990-01-11 01:33:06', '604.90', 'Ad et ullam quam et quod tempora sint et. Sunt quidem tempora reprehenderit dignissimos maxime odio sed. Perferendis doloremque ducimus iste fuga aliquid.', 'Aspernatur at iure vel maxime et.', 'Bettie Schimmel', 0, 1, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (22, 'dooley', '568 Reinger Stravenue Apt. 599\nWest Parkerburgh, VT 40541', 'blanditiis', '1974-03-17 02:42:26', '999.99', 'Deleniti quis consequatur quia sit assumenda mollitia tempora id. Eos voluptatem dolor sapiente odit. Vitae repellendus et eveniet nisi dolore et. Optio facere corporis animi culpa et tenetur. Blanditiis labore alias eligendi itaque qui eligendi.', 'Explicabo et eos sunt maxime velit cupiditate.', 'Dr. Paula Ritchie', 0, 2, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (23, 'hintzrolfson', '9358 Herman Mountain\nLake Zeldatown, MI 27411', 'eos', '1979-02-06 11:27:02', '0.00', 'Et soluta officia quo molestiae quisquam. Adipisci iusto quis illo sunt eligendi animi.', 'Ut voluptates minima eum corporis.', 'Donny Daniel Jr.', 0, 5, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (24, 'heathcote', '1373 Goyette Dale\nVirginieside, NV 32278', 'quia', '2001-12-09 13:59:49', '999.99', 'Nemo nisi et et nemo velit voluptatem. Voluptatem earum suscipit sit ea beatae. Quae sapiente libero sint est facilis inventore. Facilis molestiae provident quo.', 'Quia accusantium quis enim consectetur nesciunt.', 'Adeline Quitzon IV', 0, 10, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (25, 'erdmanconsidine', '947 Carol Hills\nKuvalishaven, AK 78669', 'illum', '1981-03-13 17:18:06', '999.99', 'Voluptatum odit explicabo rerum magnam laudantium aut et. Praesentium cumque consequatur natus eius atque.', 'Laborum facere recusandae officia veniam.', 'Dr. Haleigh Cummerata IV', 0, 7, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (26, 'lindgrenvonrueden', '6684 Antonetta Gateway Apt. 421\nEbertmouth, SD 94184', 'voluptatem', '1990-02-15 17:05:58', '1.18', 'Reprehenderit dolorem molestiae tempore. Fuga laborum numquam nostrum quia totam ea. Corporis sed voluptates voluptatem qui. Deleniti vitae est velit inventore. Aut ut consequatur non pariatur unde.', 'Expedita quo voluptatem esse pariatur aliquam enim.', 'Hayden Schneider I', 0, 2, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (27, 'johnsonryan', '9439 Conroy Pass\nDarenfort, NJ 62652', 'ab', '1979-09-30 03:26:50', '0.00', 'Qui placeat et voluptatem. Accusamus deleniti quae omnis dolore corrupti. Sit sed ea officiis dolores dolores ipsa eaque. Enim ullam in in voluptatem beatae.', 'Consequatur assumenda vitae voluptas natus.', 'Mr. Gillian Hayes V', 0, 8, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (28, 'champlin', '259 Kiehn Green Apt. 072\nPacochaberg, OR 93776', 'velit', '1977-10-20 05:28:35', '999.99', 'Doloribus similique sit mollitia modi accusamus. Hic asperiores sint rem nisi eos qui laborum. Minima sit distinctio est est repudiandae at.', 'Accusamus voluptatem ex ut dicta tempore laborum blanditiis eos.', 'Dr. Albin Wunsch DDS', 0, 9, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (29, 'grimeshessel', '5495 America Station Suite 693\nNew Cortneyville, AK 20016', 'quo', '2016-01-16 06:19:15', '14.38', 'Occaecati nam soluta facilis eos. Perspiciatis eaque et dolores vel qui atque. Cum qui deleniti dolores et nostrum iure sed.', 'Accusamus minima molestiae eos delectus.', 'Dedric Schinner', 0, 1, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (30, 'senger', '3100 Manuela View Apt. 895\nEllsworthborough, SD 33821', 'necessitatibus', '2019-07-22 05:46:44', '324.18', 'Dolor mollitia ut quibusdam quia eligendi ut. Quibusdam fugiat placeat ut sit magni ut quia. Atque numquam error nisi qui eligendi dolores rerum.', 'Sapiente et dolorum in vel incidunt autem.', 'Graham Stracke', 0, 3, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (31, 'fadelondricka', '183 Schamberger Avenue\nMacville, OR 55808-2709', 'hic', '2007-04-05 01:06:13', '0.00', 'Voluptatem a cumque eveniet consequatur et cum vel. Et accusamus qui doloremque cumque reiciendis cumque est. Rerum error est quia aliquam quae reprehenderit.', 'Nihil sequi autem quidem veniam.', 'Mireille Wisozk', 0, 3, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (32, 'bahringer', '1070 Victor Gardens Apt. 003\nLake Myrtis, MT 34289-8170', 'doloremque', '1978-12-10 20:34:15', '34.65', 'Necessitatibus nobis id quae. Soluta nam non quis dignissimos iste beatae. Qui deleniti voluptatem molestiae dolore est.', 'Dolor neque dolor sed beatae quidem unde.', 'Scotty Barton', 0, 5, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (33, 'schmitt', '854 Alec Lodge Suite 645\nPort Addisonport, NH 71671', 'similique', '2005-01-20 12:27:28', '999.99', 'Eligendi recusandae esse ut. In sint a fuga inventore provident. Dolorem doloremque reprehenderit explicabo illo et ut.', 'Sed tenetur rerum placeat.', 'Spencer Kshlerin V', 0, 7, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (34, 'swaniawski', '50514 Javonte Villages Suite 047\nWest August, LA 59739', 'quia', '1988-07-25 12:08:53', '999.99', 'Dolores consequatur non molestiae sed eaque voluptas reiciendis magnam. Cumque ut quasi dolor aut provident amet. Magni nihil laudantium aut est eum.', 'Minima quo et voluptates suscipit possimus est adipisci.', 'Prof. Lucius Nikolaus Sr.', 0, 6, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (35, 'parker', '3326 Leopold Spring\nNikoland, HI 04403', 'quibusdam', '1999-10-12 03:43:08', '999.99', 'Repellat voluptatem delectus vitae alias. Aperiam voluptas atque est aspernatur est vel reiciendis. Consectetur blanditiis velit et nobis et dolor reiciendis. Laudantium et accusantium vel corrupti. Minus odio rerum maxime quos dolor voluptas possimus.', 'At sunt dolorum veniam dolores nihil dolorem.', 'Dakota Hayes', 0, 1, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (36, 'mitchell', '70734 O\'Conner Lodge Suite 923\nNorth Keshawn, WY 50078-8566', 'ab', '1970-02-08 23:05:23', '999.99', 'Dolore provident deleniti quia et maxime. Sint temporibus sapiente quidem excepturi quam. Repudiandae et qui ea repellat.', 'Nulla recusandae quam quasi sint assumenda dolorem omnis.', 'Anika Witting', 0, 5, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (37, 'leannon', '21477 Jacobs Crossing Apt. 551\nPascalefort, MN 10235', 'non', '2001-09-21 14:21:29', '999.99', 'Voluptas enim facilis ut. Eligendi et consequatur perspiciatis explicabo. Libero ipsa omnis nesciunt consequatur est voluptates rerum. Dolorum iste suscipit non consequatur.', 'Sequi consequuntur fugit qui voluptatem et ea reiciendis.', 'Fletcher Herzog', 0, 4, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (38, 'davis', '770 Marquardt Meadow Suite 177\nBertrandland, LA 34527-3522', 'aperiam', '1981-04-27 15:57:30', '999.99', 'Autem corrupti exercitationem dolores hic aut vitae culpa. Voluptate vel perferendis tempore beatae incidunt. Laborum voluptatem dolorum sunt accusantium qui eligendi necessitatibus. Mollitia quo earum quia nihil quod.', 'Eum nesciunt et numquam totam.', 'Giovanna Altenwerth', 0, 3, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (39, 'reichel', '610 Satterfield Locks\nPort Daniella, NH 91332-8332', 'itaque', '1995-11-06 11:08:27', '999.99', 'Iure amet consequatur dicta temporibus eaque. Facilis voluptatem numquam et totam quod ut exercitationem amet. Voluptatem nam similique illo velit nostrum. Ut corrupti voluptatum esse vel sunt et.', 'Sed consequuntur esse quis commodi.', 'Jarrod Bogan', 0, 10, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (40, 'ratkestamm', '38494 Renner Course\nGreenfeldermouth, IN 53013', 'explicabo', '1994-05-20 01:37:32', '999.99', 'Doloremque ut dicta iure itaque nihil et sint. Eius est veniam culpa optio ea. Ex unde veritatis laudantium nam suscipit dolores.', 'Et deserunt et quis voluptatem quo saepe tempora.', 'Vincenzo Schaefer', 0, 8, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (41, 'rodriguezzemlak', '73970 Rau Mall\nWolfberg, ND 23034-0883', 'libero', '2000-09-06 15:49:30', '3.76', 'Rerum illum beatae quia corporis in quod excepturi. Maxime vero dolores quos aut quidem. Minus neque maiores dolore quo.', 'Quis sit omnis porro tenetur autem quia consequatur quam.', 'Stephon Ortiz', 0, 2, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (42, 'caspercronin', '43299 Schneider Skyway\nBotsfordport, PA 11021', 'ab', '1973-09-25 11:17:38', '999.99', 'Ducimus esse tempore tenetur temporibus explicabo accusamus et. In nemo sed quidem distinctio. Enim consectetur ducimus architecto autem.', 'Est ducimus impedit quia eveniet doloremque.', 'Edd Dibbert I', 0, 2, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (43, 'pagac', '76695 Schmidt Club Apt. 729\nPort Giuseppe, AK 86926-3845', 'qui', '2007-08-13 12:19:56', '999.99', 'Vel et nostrum ut. Perferendis quaerat voluptas consequuntur magni. Voluptas reprehenderit occaecati facere ducimus commodi.', 'Et molestiae dignissimos voluptatem ea.', 'Araceli Schmitt', 0, 8, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (44, 'cormier', '62931 Terrence Mill\nWest Caesar, OR 83272-9470', 'ea', '2006-11-26 04:55:12', '999.99', 'Eius optio ab voluptas voluptatem. Sunt eveniet dolorum enim eveniet tempora rerum. Voluptates a velit consequatur repellendus et. Aut odio id voluptas provident et.', 'Quas non voluptas debitis molestias repellendus.', 'Baylee Gerlach DDS', 0, 7, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (45, 'herman', '526 Trantow Gardens Apt. 390\nEast Osbaldomouth, VA 65762-0149', 'porro', '1975-04-10 07:44:15', '999.99', 'Occaecati consequatur molestiae accusantium est reprehenderit asperiores dignissimos. Dolores odio fugiat vero neque eos atque accusamus sunt. Vitae praesentium et est distinctio id.', 'Amet minima recusandae praesentium aut in labore recusandae beatae.', 'Prof. Alyce Abbott DVM', 0, 5, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (46, 'bergstrom', '76176 Lynch Heights\nFayfurt, HI 55435', 'optio', '1972-01-12 21:56:34', '999.99', 'Velit eaque eum non ipsa voluptas. Quidem aperiam consequuntur eum aut expedita asperiores voluptates. Ut porro aperiam est. Magnam doloremque commodi recusandae eos. Sunt qui expedita itaque ut eos recusandae.', 'Aspernatur sed ipsum at non atque est.', 'Maymie Gutmann', 0, 6, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (47, 'legrosmarquardt', '65650 Kathlyn Parks Apt. 230\nEast Myaport, OK 12531', 'occaecati', '1991-02-06 15:15:39', '999.99', 'Voluptatem voluptatem tempora consequatur minima. Et natus est nihil aut hic quas veniam.', 'Sit dolor omnis quo ut aspernatur nostrum.', 'Araceli Williamson', 0, 7, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (48, 'connelly', '218 Dulce Ridge Apt. 160\nNew Armanimouth, MS 31270', 'veritatis', '1973-02-15 21:58:20', '999.99', 'Aperiam illo exercitationem unde expedita quia. Quibusdam iste id facere libero dolor. Totam magnam eos labore dicta vel nobis.', 'Molestias velit ut est.', 'Breanne Lesch', 0, 9, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (49, 'padberg', '43649 Rachelle Route\nWest Jonatanport, MI 42664-6355', 'vitae', '1988-01-19 14:22:43', '999.99', 'Rerum ducimus expedita sit ratione dolor voluptatibus. Exercitationem omnis facere repudiandae debitis odio sunt nesciunt. Ut repudiandae tempora vitae vero voluptatibus. Sequi quo aut voluptatem et consequuntur quam id.', 'Qui autem assumenda accusamus facilis qui.', 'Prof. Magali Ernser', 0, 4, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (50, 'haagwilkinson', '147 Swaniawski Divide\nHellerport, UT 49450-6778', 'totam', '1998-12-05 18:27:10', '0.00', 'Enim non perspiciatis autem cupiditate. Aliquid qui quis enim accusamus sed consequatur. Aspernatur illum nihil nihil aspernatur vel enim commodi. Ea sint culpa et fugiat suscipit.', 'Sit dolore et doloribus eum architecto quas deleniti.', 'Gene McKenzie', 0, 6, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (51, 'kling', '944 McCullough Extensions Suite 499\nHermannton, NE 20573-5135', 'rerum', '1998-03-19 10:06:20', '999.99', 'Illo quis modi voluptatem non aspernatur error eos. Occaecati sunt quas explicabo voluptas omnis et tempore. Illum a quo et minima. Minima tempora accusantium quia ut accusantium.', 'Sed repudiandae et et quod.', 'Mitchel Gislason', 0, 9, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (52, 'schusterschuster', '903 Christine Grove Apt. 362\nLake Denatown, VT 12823-8354', 'suscipit', '1995-04-20 07:02:35', '90.38', 'Aut earum iusto quis perspiciatis. Eaque fugiat rerum dignissimos delectus aliquam cupiditate id doloribus. Soluta rerum perferendis qui eaque. Corrupti quo aspernatur provident voluptatem aspernatur optio velit.', 'Perspiciatis possimus debitis dolores ratione.', 'Cristobal Mante', 0, 6, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (53, 'blanda', '2810 Junius Islands Apt. 584\nSouth Erichside, UT 94456-4564', 'in', '1979-03-23 14:02:50', '999.99', 'Consectetur ea quam id deserunt distinctio et. Nemo aut maiores doloremque. Culpa et alias ea voluptas unde error. Quia vel dolor animi exercitationem ut.', 'Molestias et quam et laboriosam amet sit.', 'Ila Koepp', 0, 8, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (54, 'torphy', '72666 Richmond Dale\nArttown, SD 70973-2374', 'odio', '1978-08-10 03:07:46', '999.99', 'Ipsum dolores cumque suscipit dolorem. Amet atque non quam id corrupti. Harum deserunt eum consequuntur quis sit commodi ullam. Error reprehenderit facilis accusantium cupiditate aliquam alias.', 'Ut odio praesentium voluptatem tempore assumenda.', 'Brenna Dicki', 0, 10, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (55, 'schaefer', '9885 Romaguera Station\nAiyanaton, WV 77062', 'placeat', '1987-09-25 00:42:24', '0.00', 'Nisi incidunt ullam nulla voluptate. Exercitationem est aperiam est voluptas.', 'Qui voluptas aliquid delectus est deserunt illo.', 'Jeanne Macejkovic', 0, 1, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (56, 'runolfsdottirlindgren', '245 Quitzon Station Apt. 150\nSouth Margarettaborough, NC 77107-5796', 'vitae', '1976-12-04 08:55:57', '8.11', 'Ducimus unde fugiat aperiam expedita eaque. Iste quam occaecati optio eum. Adipisci nihil exercitationem ea alias magnam.', 'Aperiam velit rerum voluptatem neque.', 'Mikayla Huel', 0, 3, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (57, 'romaguera', '2634 Stephany Prairie\nSouth Gerardview, LA 84266', 'eaque', '1983-05-22 05:58:14', '49.50', 'Laudantium quibusdam et odit. Libero minus provident quasi autem quos quasi recusandae. Dolor inventore eos voluptatibus officia culpa. Magni beatae dolor veniam error occaecati et officia dolores. Dicta et similique dolorem consequuntur at nulla doloremque.', 'Aut minima voluptates veritatis doloremque.', 'Domenick Douglas', 0, 8, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (58, 'gleasonquitzon', '019 Sim Row Suite 807\nSouth Clarissa, KS 48728-6684', 'consequatur', '2016-11-17 20:13:56', '91.39', 'Aut asperiores est cupiditate eaque nostrum. Ea aut sed occaecati. Perferendis minus omnis hic qui ut.', 'Nam qui dolorem recusandae dolores ea.', 'Annette Von', 0, 2, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (59, 'herzog', '822 Charlotte Motorway\nNew Wellingtonshire, KS 40908', 'totam', '1980-03-19 00:04:00', '0.00', 'Et omnis eius suscipit maiores ipsa debitis. Qui possimus nesciunt temporibus ipsum nemo. Nihil et deleniti asperiores cum est tempore enim. Et architecto dolorum repellat inventore.', 'Tempora officia aperiam corporis et ut hic.', 'Amos Bergnaum', 0, 4, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (60, 'stanton', '097 Joan Light Suite 346\nMuellershire, NJ 50405-1109', 'quia', '2012-07-03 00:46:57', '5.12', 'Molestiae laboriosam dolorum necessitatibus. Dolorum ad molestias voluptatem error quis tempore illo.', 'Magni velit enim a ipsam consequatur ut doloribus voluptatem.', 'Ms. Alena Crona PhD', 0, 3, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (61, 'senger', '24998 Lawson Stream Apt. 481\nPetehaven, KY 57260', 'repellendus', '1997-03-22 03:05:56', '999.99', 'Eos recusandae aut nesciunt doloremque doloremque cum libero tempora. Consequatur est consequatur pariatur laboriosam enim error. Quo non praesentium et iste distinctio. Optio nam aperiam et voluptatum corporis eos qui.', 'Ut dignissimos sapiente eum ad sit sint exercitationem.', 'Rebekah Monahan DVM', 0, 9, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (62, 'flatley', '909 Emilio Throughway Suite 483\nEast Brennamouth, AZ 61964', 'illo', '1980-11-18 14:59:58', '999.99', 'Exercitationem est ad et impedit non labore quas. Qui voluptatibus dolore consequatur nisi quod aut. Est quidem eum quisquam aut. Ut qui animi repellendus consectetur.', 'Molestiae excepturi non dicta eos.', 'Mrs. Tiara Douglas', 0, 6, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (63, 'muller', '711 Schmitt Roads Suite 933\nSouth Charlesmouth, SC 77022', 'incidunt', '2011-09-27 00:26:47', '999.99', 'Maxime sequi nihil cumque eum quia. Expedita voluptatibus nesciunt placeat sit quia. Similique dolore iure possimus vel.', 'Doloremque perferendis occaecati possimus ab.', 'Mr. Cale Bradtke', 0, 8, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (64, 'schamberger', '35746 Jackie Valleys Apt. 862\nWest Andymouth, HI 56371', 'culpa', '1980-08-08 08:30:12', '82.92', 'Ut vel praesentium minus molestiae. Placeat est debitis ipsa labore voluptas. Sit sequi numquam quidem iste dolorem. Vitae et quibusdam est possimus praesentium deleniti molestiae. Pariatur eum soluta veritatis similique.', 'Similique eveniet ab et quis.', 'Dr. Delmer Runolfsdottir', 0, 9, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (65, 'gerlachreilly', '192 McLaughlin Prairie\nNorth Kenyonfort, AL 46420-5919', 'delectus', '2012-10-05 14:34:52', '129.48', 'Veritatis mollitia quia ea ut quos magni numquam. Ea animi et eum quia. Animi expedita error eaque perferendis sed. Eum et neque quo eos enim fugit quae quaerat.', 'Voluptatem possimus nulla possimus sunt aut.', 'Ed Bailey II', 0, 8, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (66, 'jacobs', '398 Huels Pass Apt. 542\nDickiburgh, SD 28274', 'ut', '2013-07-12 17:29:43', '2.41', 'Consequatur vel et numquam et ex. Suscipit nisi consequatur reprehenderit ipsum ea voluptatem provident quos. Illo iure exercitationem laborum cumque ad earum repellat.', 'Sed dolorem at deserunt soluta.', 'Dustin Grady', 0, 5, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (67, 'krajcik', '67418 Ramona Forks Apt. 583\nSouth Ruth, NJ 86277', 'libero', '1981-06-03 07:08:03', '999.99', 'Illo eos doloribus architecto officia illum. Quaerat incidunt quaerat et quae et similique. Ut minima et animi cumque voluptatem ex in.', 'Sed laudantium ut corrupti harum deserunt.', 'Patrick Harris', 0, 6, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (68, 'johnson', '999 Hayden Park\nSchroedermouth, KS 11953-9289', 'quia', '1988-11-06 10:39:12', '999.99', 'Rerum saepe non voluptatem et non quas provident ut. Soluta laudantium quia aut occaecati. Qui labore explicabo unde molestiae ut delectus quam.', 'A et aperiam in itaque eius.', 'Prof. Lon Collier Sr.', 0, 10, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (69, 'westturcotte', '74094 Isac Groves Apt. 031\nWest Robb, OK 09682', 'dolor', '2019-05-14 14:10:43', '999.99', 'Cumque consectetur eos voluptas blanditiis qui excepturi. Magnam velit sequi nihil consequatur. Accusantium sunt quia delectus.', 'Quia veritatis voluptas eligendi id saepe eligendi aut.', 'Vivian Rodriguez', 0, 10, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (70, 'willmsbrown', '498 Walker Islands Suite 645\nSouth Emelia, VT 22420', 'occaecati', '1998-02-24 01:13:51', '999.99', 'Provident voluptatem molestias rerum quis porro eius minus numquam. Nulla voluptatem quisquam sunt in ut. Ut libero qui est repellat et delectus quis voluptatem.', 'Asperiores laborum eveniet unde quae rerum non molestiae omnis.', 'Magnus Lakin IV', 0, 10, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (71, 'marvin', '637 Mosciski Spur Apt. 053\nEdmondmouth, AL 13648-6950', 'in', '1983-11-03 20:18:00', '0.06', 'Sed odit dolorem consectetur hic voluptas. Saepe voluptatem eos ut dolore soluta qui voluptatem. Soluta voluptatem quam possimus omnis natus. Et porro nam voluptatem autem.', 'Aspernatur consequuntur quisquam aspernatur laudantium aperiam.', 'Millie Waters', 0, 7, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (72, 'sawaynkihn', '0567 Herman Lodge\nSchummhaven, NJ 53026', 'excepturi', '2013-04-16 10:58:48', '999.99', 'Omnis excepturi dolor explicabo illo consequatur sit. Eum aut nemo molestias nesciunt voluptas et veniam. Expedita voluptatem voluptatibus omnis reiciendis labore. Non earum qui culpa et iure.', 'Aliquam quis consequuntur est incidunt dolores.', 'Verona Doyle', 0, 3, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (73, 'corwin', '0262 Reichel Forges\nGraceborough, SC 06351-2011', 'excepturi', '2007-05-15 18:39:45', '999.99', 'Reiciendis sequi nihil accusamus odio error deleniti sint. Atque quas unde rerum atque sed. Voluptatem mollitia molestias maxime alias vitae possimus iusto. Eaque id assumenda molestias nam ipsum eius ea.', 'Dolorem aliquid fugiat mollitia.', 'Hollie Hand', 0, 6, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (74, 'davisgleason', '175 Dena Brooks\nCorwinstad, MD 30030', 'quo', '2020-06-06 08:41:20', '999.99', 'Facere et laudantium a animi et error nam. Cum ipsam nisi enim fugit similique esse. Cumque quis iste architecto. Quia et qui non facilis est iste.', 'Soluta minus reprehenderit magni et.', 'Maybelle Adams PhD', 0, 9, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (75, 'west', '98723 Kris Harbors Apt. 703\nNew Pinkstad, CO 84188', 'voluptas', '2020-11-26 09:41:46', '999.99', 'Quia eum occaecati dolorum similique adipisci sed. Esse reprehenderit voluptas veniam et culpa nesciunt perspiciatis quis.', 'Magni sint voluptatum temporibus ipsum reprehenderit adipisci reiciendis.', 'Mr. Orland Rath V', 0, 4, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (76, 'schimmel', '0792 Kling Land Suite 391\nNew Keyonchester, ME 68956-2246', 'et', '1983-06-13 21:55:17', '145.90', 'Quos minima aperiam consequatur qui iusto eum. Eligendi quo ut optio id voluptas enim necessitatibus totam. Quasi ut odio totam quo.', 'Beatae cumque sed rerum aut molestiae qui eligendi consectetur.', 'Beth Kertzmann', 0, 7, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (77, 'hamillwisoky', '70465 Hadley Plains Apt. 443\nNorth Mikeshire, MA 53935-2484', 'eligendi', '1978-04-12 19:37:30', '999.99', 'Necessitatibus quia dolore vel quia doloribus. Autem ut minima aut voluptas molestiae porro. Assumenda nesciunt atque dignissimos et consequatur reprehenderit praesentium voluptas.', 'Omnis quos ab illo eos.', 'Dr. Eugenia Larkin', 0, 9, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (78, 'ritchie', '80137 Alden Inlet Suite 182\nSouth Bobbybury, NY 19402-5206', 'doloribus', '2009-04-13 22:51:10', '1.77', 'Voluptatem dolor ab maiores est error architecto. Voluptatem dolorem omnis et voluptas qui repudiandae sit nemo. Rerum praesentium at suscipit enim eligendi rem. Ex atque et dolor.', 'Earum temporibus ipsam ipsam voluptas consequatur.', 'Ayden Jerde', 0, 9, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (79, 'reichert', '761 Angelina Junction Apt. 562\nWest Amya, NE 22835', 'dolores', '1988-02-07 03:01:10', '999.99', 'Nostrum voluptate nihil dolorem. Sit unde ut dolorem voluptates nemo ut. Ipsum omnis neque adipisci quis aut voluptas qui. Iusto non quos perspiciatis minus consequatur est. Voluptas ab veritatis ea repudiandae minima ducimus assumenda.', 'Amet quos consequatur doloremque quia nemo temporibus laudantium.', 'Dr. Domingo Adams IV', 0, 7, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (80, 'baumbach', '16688 Cristian Meadow\nSouth Francis, WI 23938-9673', 'possimus', '2002-08-31 18:08:01', '999.99', 'Qui voluptatem deleniti sed excepturi consequatur. Assumenda aut officiis voluptatem qui. Reprehenderit corporis qui non repudiandae minima laboriosam aliquam.', 'Quod sapiente rerum sunt dolorem impedit adipisci.', 'Una Friesen', 0, 6, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (81, 'wunschmccullough', '4704 Kaley Via Apt. 317\nLindburgh, TN 28572', 'quo', '1990-03-01 08:41:30', '999.99', 'Sit rem esse voluptatem non quam. Quo quod aliquid dolor ducimus nesciunt et sequi. Velit qui deleniti ipsam maiores est error. Consectetur qui minus odit nihil.', 'Aspernatur non nostrum ut.', 'Giuseppe Langosh MD', 0, 2, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (82, 'berge', '186 Jerde Crossing Apt. 167\nBinsville, NV 17819', 'dolore', '1971-08-20 11:24:45', '999.99', 'Qui assumenda maiores ea quos fugiat eius libero recusandae. Et recusandae qui cupiditate ut id. Assumenda quia numquam dolor aperiam tenetur. Ratione et accusamus aliquid quo asperiores qui et. Esse explicabo dolorem repellendus dolor in sed.', 'Ipsa nihil et et qui.', 'Ashlynn Frami IV', 0, 1, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (83, 'willmsmoen', '838 Johnston Via\nFramistad, FL 81359-9859', 'temporibus', '1991-08-22 05:33:53', '0.00', 'Dignissimos optio sit facilis iste fugit qui vel soluta. Magni voluptas expedita sint ex et. Cum cumque in fugiat pariatur iure ipsum est.', 'Esse dolor enim perferendis dolorem facilis provident.', 'Mack Fisher', 0, 2, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (84, 'stiedemannflatley', '6436 Pouros Stravenue\nJerroldburgh, NV 33277', 'minima', '1998-01-28 16:50:09', '5.87', 'Modi dignissimos enim quas necessitatibus est sequi. Sint suscipit distinctio nemo quo explicabo. Voluptas eos ratione consequatur aut.', 'Sed voluptates fugiat eos quos.', 'Deion Cole', 0, 10, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (85, 'gerholdhoeger', '42394 Hadley Ferry\nHoweville, UT 81182', 'eius', '1976-02-21 01:54:15', '999.99', 'Veritatis quisquam nostrum reiciendis sapiente eius reiciendis aut cumque. Repudiandae commodi tempore voluptatum modi aliquid quo. Et quis rerum aperiam hic.', 'Et rem saepe officiis.', 'Eusebio Vandervort', 0, 9, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (86, 'bartell', '335 Crona Dale\nWaelchihaven, ID 42594', 'quia', '1996-06-01 18:24:01', '0.55', 'Omnis consequatur voluptates et doloribus. Molestias eum nihil et est officiis ut. Dolor nihil quas ea autem provident consequatur voluptatem.', 'Expedita beatae nobis soluta corrupti eum maiores.', 'Brice Hamill', 0, 2, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (87, 'reichertreinger', '45190 Mante Forks\nJenkinsside, KY 74805-8991', 'dolor', '2018-10-23 21:13:51', '999.99', 'Sapiente ipsum hic inventore. Eligendi culpa temporibus et quibusdam nemo tenetur sed. Et veniam laudantium nihil. Minima aut voluptate neque.', 'Perferendis quia tempora maxime ipsam dicta sit vero.', 'Jewell Erdman', 0, 2, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (88, 'hermannhuel', '67663 Schoen Village\nSchimmeltown, MA 77590', 'modi', '1980-12-07 11:21:22', '12.63', 'Sunt quis quaerat ut quia quia aut. Nihil mollitia nisi culpa ea. Velit ut temporibus impedit facilis placeat ratione iure.', 'Repellat aut illo deleniti beatae repellat repellendus nam.', 'Lonie Gibson', 0, 10, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (89, 'beatty', '07925 Stoltenberg Fork\nCelestineport, OR 57460-0599', 'velit', '1993-08-31 01:23:01', '999.99', 'Reiciendis ea voluptates fugiat nobis mollitia molestiae ut. Officiis error sapiente et fugit. Sint minima ut tempore et. Architecto et non in.', 'Iure quam expedita quos harum consequuntur dolorem aperiam.', 'Elta Hoeger', 0, 10, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (90, 'conroycrona', '82845 Sydnie Unions\nKeenanstad, NC 43176', 'mollitia', '1994-11-11 18:29:29', '999.99', 'Voluptatibus autem praesentium fuga rem aspernatur. Commodi qui tempora architecto magnam. Velit veritatis earum est perspiciatis molestiae ut.', 'Odit quo quia voluptates qui iure culpa ratione.', 'Prof. Lorenzo Mann Sr.', 0, 6, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (91, 'will', '608 Quigley Greens\nWest Leone, NJ 04377-1377', 'minus', '1991-05-29 21:09:44', '999.99', 'Repudiandae quos similique ut quam odio tempore doloremque. Perferendis inventore dolorum perspiciatis aut voluptate. Eveniet amet labore in optio culpa vel.', 'Et saepe praesentium porro cupiditate minus sequi quisquam.', 'Mittie Hamill', 0, 9, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (92, 'tillman', '5206 Eudora Ramp Suite 548\nSouth Reba, MN 53296-6110', 'ipsam', '1990-05-05 15:59:56', '999.99', 'Illo repellat eos saepe voluptates dicta iste nemo. Expedita quam est placeat ipsum nemo quis sed. Neque sunt optio ut laboriosam. Veniam odit ducimus est soluta ut aut sequi.', 'Tenetur est sed autem sint aspernatur quisquam non.', 'Leanna Turner', 0, 7, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (93, 'rice', '238 Ludwig Tunnel\nSchmelerview, WA 57292-1986', 'vitae', '1995-03-08 17:44:47', '50.15', 'Consequatur modi ut sunt id voluptatem. Quaerat porro rerum eius molestiae. Ut laudantium laboriosam sapiente iure ut natus laudantium. Nesciunt quibusdam doloremque laborum qui est iure.', 'Provident minus rem impedit.', 'Mariah Schuppe', 0, 5, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (94, 'jast', '96901 Tianna Skyway\nNorth Orenchester, ND 86249-7019', 'dolorem', '1979-03-12 21:03:17', '999.99', 'Quidem occaecati dolorem minima iusto. Facilis dolor tempora non ducimus id. Ut eos ea eligendi sit officia in minima hic. Repudiandae voluptas sint consectetur voluptas odio rem.', 'Aperiam voluptatibus ut ullam.', 'Marshall Hammes', 0, 2, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (95, 'prosacco', '74019 Kessler Islands\nPort Bernhardborough, IN 51839', 'esse', '1976-02-14 23:59:18', '999.99', 'Similique ducimus quae sit ut temporibus. Molestias modi nisi dolor vel. Quia voluptas accusamus neque id iure aperiam blanditiis. Consequatur magnam quibusdam velit quia dolorem.', 'Quis autem blanditiis optio deserunt.', 'Mrs. Estefania Herzog', 0, 1, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (96, 'larkin', '9383 Macey Unions Apt. 534\nEast Velda, IA 32399', 'sed', '1982-05-01 23:29:01', '0.00', 'Molestiae quis voluptates est rerum reiciendis debitis at doloribus. Facere molestias ad nihil officiis minima quis. Itaque corrupti architecto minus laudantium. Quasi eos hic beatae quaerat eos.', 'Incidunt consequatur est quidem est.', 'Derick Parker', 0, 5, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (97, 'graham', '661 Rocky Lodge\nKulasbury, WV 40365', 'sunt', '1978-04-13 05:01:35', '999.99', 'Rerum sed pariatur est sint sapiente. Et nostrum excepturi autem aliquam id et. Iste assumenda distinctio et nisi est laborum. Adipisci fugiat aut neque aut.', 'Ut neque molestiae minima.', 'Prof. George Veum IV', 0, 9, 2);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (98, 'walker', '033 Amalia Circles Apt. 244\nKraigstad, MN 13093', 'consequatur', '2007-06-30 03:07:41', '1.19', 'Et et ut quaerat maxime ea. Quisquam voluptatem suscipit est et ea. Quis molestiae consequatur dolores ab.', 'Assumenda voluptas dolores officia omnis voluptate alias nulla.', 'Dr. Duane McKenzie', 0, 9, 1);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (99, 'rodriguezparisian', '377 Botsford Groves\nImeldaburgh, WA 90409', 'facere', '1970-03-21 09:40:05', '298.91', 'Voluptatum sit aut molestiae nisi porro sunt aut. Molestiae non in ratione et.', 'Aut quidem atque corporis quibusdam.', 'Joannie Ernser', 0, 6, 3);
INSERT INTO `Course` (`course_id`, `type`, `address`, `name`, `scheduled`, `price`, `description`, `title`, `instructor`, `capacity`, `citation_type_id`, `school_id`) VALUES (100, 'haley', '45393 Ziemann Trace Suite 917\nLake Thaddeus, WY 70866', 'ipsum', '1994-02-21 03:25:29', '140.20', 'Ipsum maxime voluptatibus unde non aut laborum odit. Tempore eos adipisci non beatae molestiae laudantium et. Facere ut quo facere corporis qui porro. Ipsum eos autem quia sit.', 'Voluptatem unde velit id neque soluta enim.', 'Kaleb Mayert', 0, 2, 2);


